#!/bin/bash

if [[ $# == 2 ]]; then
  PORT=`nmap -p 49000-50000 $1 | grep open | tail -1 | cut -d\/ -f1`
  if [[ $PORT == "" ]]; then
    echo "Error: $1 is not a Belkin WeMo Switch"
    exit 1
  fi
  case $2 in
  status)
    XML=`curl -silent http://$1:$PORT/setup.xml`
    STATE=`(curl -A '' -X POST \
      -H 'Content-type: text/xml; charset="utf-8"' \
      -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#GetBinaryState"' \
      -s http://$1:$PORT/upnp/control/basicevent1 \
      --data '<?xml version="1.0" encoding="utf-8"?>
        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
          <u:GetBinaryState xmlns:u="urn:Belkin:service:basicevent:1"/>
        </s:Body>
      </s:Envelope>'
      ) | sed -n 's/<BinaryState>\(.\)<\/BinaryState>/\1/p'`
    SIGNAL=`(curl -A '' -X POST \
      -H 'Content-type: text/xml; charset="utf-8"' \
      -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#GetSignalStrength"' \
      -s http://$1:$PORT/upnp/control/basicevent1 \
      --data '<?xml version="1.0" encoding="utf-8"?>
        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
          <u:GetSignalStrength xmlns:u="urn:Belkin:service:basicevent:1"/>
        </s:Body>
      </s:Envelope>'
      ) | sed -n 's/<SignalStrength>\(.*\)<\/SignalStrength>/\1/p'`
    echo "Name: `echo $XML | grep -oPm1 '(?<=<friendlyName>)[^<]+'`"
    echo "Model: `echo $XML | grep -oPm1 '(?<=<modelName>)[^<]+'`"
    echo "Status: $STATE"
    echo "IP Address: $1"
    echo "Signal Strength: $SIGNAL"
    echo "MAC Address: `echo $XML | grep -oPm1 '(?<=<macAddress>)[^<]+'`"
    echo "Serial Number: `echo $XML | grep -oPm1 '(?<=<serialNumber>)[^<]+'`"
  ;;
  on)
    curl -A '' -X POST \
      -H 'Content-type: text/xml; charset="utf-8"' \
      -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#SetBinaryState"' \
      -s http://$1:$PORT/upnp/control/basicevent1 \
      -o /dev/null \
      --data '<?xml version="1.0" encoding="utf-8"?>
        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
          <s:Body>
            <u:SetBinaryState xmlns:u="urn:Belkin:service:basicevent:1">
              <BinaryState>1</BinaryState>
            </u:SetBinaryState>
          </s:Body>
        </s:Envelope>'
  ;;
  off)
    curl -A '' -X POST \
      -H 'Content-type: text/xml; charset="utf-8"' \
      -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#SetBinaryState"' \
      -s http://$1:$PORT/upnp/control/basicevent1 \
      -o /dev/null \
      --data '<?xml version="1.0" encoding="utf-8"?>
        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
          <s:Body>
            <u:SetBinaryState xmlns:u="urn:Belkin:service:basicevent:1">
              <BinaryState>0</BinaryState>
            </u:SetBinaryState>
          </s:Body>
        </s:Envelope>'
  ;;
#  rename)
#    curl -A '' -X POST \
#      -H 'Content-type: text/xml; charset="utf-8"' \
#      -H 'SOAPACTION: "urn:Belkin:service:basicevent:1#ChangeFriendlyName"' \
#      -s http://$1:$PORT/upnp/control/basicevent1 \
#      -o /dev/null \
#      --data '<?xml version="1.0" encoding="utf-8"?>
#        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
#          <s:Body>
#            <u:ChangeFriendlyName xmlns:u="urn:Belkin:service:basicevent:1">
#              <FriendlyName>$3</FriendlyName>
#            </u:ChangeFriendlyName>
#          </s:Body>
#  ;;
  *)
    echo "Error: $2 is not a valid command"
  ;;
  esac
else
  echo "Usage: wemo <IP address of Belkin WeMo Switch> <command>"
  echo
  echo "Valid commands: status  on  off"
  exit 1
fi
